steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "build and submit the dataflow job"
    name: maven:3.6.0-jdk-11-slim
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args: ['-m', 'main',
          "--project=tiger-mle",
          "--stagingLocation=gs://beampipeline/staging/",
          "--gcpTempLocation=gs://beampipeline/temp/",
          "--runner=DataflowRunner",
          "--autoscalingAlgorithm=THROUGHPUT_BASED",
          "--maxNumWorkers=10",
          "--jobName=demo",
          "--buildNumber=${buildNumber}",
          "--region=us-east1"
          ]
    waitFor: ['get build number']
